name: pull-request

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --release --target web sand_evolution_lib
